### ISSUE TITLE
Fix test coverage issue

### ISSUE THREAD

**Issue by oskar-codes** [SwEnt-Group13/Unio#177]
SonarCloud currently doesn't correctly retrieve the coverage data when uploaded from the CI. This is an issue that was introduced with [#155](https://github.com/SwEnt-Group13/Unio/pull/155). See [this issue](https://github.com/SwEnt-Group13/Unio/issues/134) for further details.

**Comment by oskar-codes** [comment]
After running `./gradlew check connectedCheck jacocoTestReport`, the coverage report shows very low code coverage. Thus, the issue might not be with Sonar not correctly retrieving the coverage, but actually with JaCoCo, or Android Orchestrator. I will look into this now.

Note that I swear I had 70% code coverage when running JaCoCo yesterday, but it seems like that's not the case anymore.

**Comment by oskar-codes** [comment]
I removed Android Orchestrator in order to keep the coverage data between tests and increase testing speed, but now the mocks reappear in the end to end tests.
After further research I have confirmed that the issue is linked with Hilt. Mocked repositories are included in the end to end tests because Hilt injects them with `@TestInstallIn` calls in `HiltModules.kt`.

I am currently trying to find a way to separate end-to-end tests from the rest of the UI tests so that Hilt only injects mocks in the UI tests.

**Comment by oskar-codes** [comment]
According to [the official documentation](https://developer.android.com/training/dependency-injection/hilt-testing#replace-binding), Hilt only allows the replacement of production modules with two methods:
- You create a new module annotated with `@TestInstallIn` which then applies itself to **every** test in the `androidTest` package
- You manually uninstall the production modules from a test class and write the replacement module inside that class
That means you can either replace modules in all test classes, or one at a time.
This imposes an issue for our test structure, because we have end to end tests that should not have any module replaced, and UI tests that need their modules replaced.

Thus, I see two options: we either manually uninstall modules and write the replacement module in each and every UI test, or we remove Hilt from the project.

**Comment by Zafouche** [comment]
> According to [the official documentation](https://developer.android.com/training/dependency-injection/hilt-testing#replace-binding), Hilt only allows the replacement of production modules with two methods:
> 
> * You create a new module annotated with `@TestInstallIn` which then applies itself to **every** test in the `androidTest` package
> * You manually uninstall the production modules from a test class and write the replacement module inside that class
> 
> That means you can either replace modules in all test classes, or replace modules one at a time. This imposes an issue for our test structure, because we have end to end tests that should not have any module replaced, and UI tests that need their modules replaced.
> 
> Thus, I see two options: we either manually uninstall modules and write the replacement module in each and every UI test, or we remove Hilt from the project.

I have concluded pretty much the same results. 

Using the emulated `Firestore` means using the actual view models and repositories w/o mocking them. Hilt propagates them throughout all test files for some reason, meaning they sometimes might be carried on between different test files, and that causes problems. On my side, it makes it such that only the login e2e test passes, while the other e2e fails and cancels the entire `connectedCheck` (it does not carry on to running the other remaining tests), meaning it runs into a fatal crash.

Now if we mock all the modules in the `HiltTestUtility.kt` file, that means mocking the entire e2e and it defeats the purpose of the emulated `Firestore`.

So after some research, I have seen similar practices as to what @oskar-codes mentioned. 
I have also seen some people writing chain rules, which I am still investigating, however that also means creating multiple classes to finally be able to inject something in 1 test file, so that seems a little sketchy. I haven't seen anyone have the same problem as us, so I am still investigating how `Hilt` can be used, however at this point it feels like, instead of making life easier, `Hilt` just makes it more difficult. It is a pretty complex library after all.

**Comment by oskar-codes** [comment]
The issue has finally been resolved and has been merged into main with #174. However it must be noted that this is a **temporary** fix. An issue remains, namely that the order of execution of the tests matters. When trying to fix this issue, I decided to separate end to end tests files from UI test files by placing them in a separate directory, but this inadvertently made them execute **before** all other tests.

After closing this issue and merging the fix into main, I noticed that running the end to end tests **after** all the others sadly made them fail due to a MockK stubbing error. It appears that mocked repositories are still somehow appearing in the end to end tests.

I might investigate this sometime, but it is now less of a priority while we have the temporary fix.
